# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIBQRIdmrwznd6Ng0S0w0AGWg7-HVDN5
"""

import streamlit as st
import numpy as np
import onnxruntime as ort

@st.cache_resource
def load_model():
    return ort.InferenceSession(r"C:\Users\mohamed\decision_tree_onnx_app\heart_desicion_tree.onnx")

session=load_model()
st.title("Heart Disease Prediction")
st.write("Enter the following details to predict heart disease")
input_str=st.text_input("Enter the input string")
if st.button("Predict"):
    try:
        input_array = np.array([list(map(float, input_str.strip().split(',')))], dtype=np.float32)
        input_name = session.get_inputs()[0].name
        ort_inputs = {input_name: input_array}
        pred = session.run(None, ort_inputs)
        st.write("Result:", pred[0][0])
    except Exception as e:
        st.error(f"Error occurred: {e}")